### ISSUE TITLE
UI Event spec modernization task list

### ISSUE THREAD

**Issue by garykac** [w3c/uievents#370]
This tracks the tasks that need to be completed in order to modernize the UI Events spec.

* [ ] Begin discussion and get agreement on splitting spec into smaller parts (see https://github.com/w3c/uievents/issues/369)
* [ ] Split the spec into separate documents:
   * [ ] Freeze the spec
   * [ ] Flush all pending pull requests
   * [ ] Split the spec into separate parts
   * [ ] Unfreeze the specs
* [ ] Update SpecRef (et al) to point to new specs
* [ ] Migrate current algorithms into specs:
   * [ ] UI Events core
   * [ ] Composition
   * [ ] Focus
   * [ ] Input
   * [ ] Keyboard
   * [ ] Mouse
   * [ ] Wheel

**Comment by mustaqahmed** [comment]
FYI @plehegar @patrickhlauke @flackr We discussed the need for algorithmic event dispatch text in Pointer Events [few weeks ago](https://lists.w3.org/Archives/Public/public-pointer-events/2024AprJun/0006.html), and concluded that we need to wait for the [UI event algorithms](https://w3c.github.io/uievents/event-algo.html) to land first.
